export const GETPROJECTREQ     = "GETPROJECTREQ";
export const GETPROJECTSUCESS  = "GETPROJECTSUCESS";
export const GETPROJECTFAILURE = "GETPROJECTFAILURE";


export const GETPROJECTCREATEREQ     = "GETPROJECTCREATEREQ";
export const GETPROJECTCREATESUCESS  = "GETPROJECTCREATESUCESS";
export const GETPROJECTCREATEFAILURE = "GETPROJECTCREATEFAILURE";
